grille:=false;ordre:='';epee:=false;tableau:=false;essuie:=false;lave:=false;bombe:=false;mouchoir:=false;bouteille:=false;
clef:=false;vaiselle:=false;lampe:=true;collier:=false;fantome:=false;p_hall:=false;p_salon:=false;cave_ecl:=false;
3,$E3,$F7,$F7,$22,$F7,$E3);
      rond1 : FillPatternType = ($FF,$FF,$7E,$BD,$BD,$7E,$FF,$FF);
      rond2 : FillPatternType = ($FF,$3C,$DB,$DB,$DB,$DB,$3C,$FF);
