ECHO OFF
CLS
if %1==1 goto continue1
if %1==2 goto continue1
if %1==3 goto continue1
if %1==4 goto continue1
if %1==5 goto continue1
if %1==6 goto continue1
if %1==7 goto continue1
if %1==8 goto continue1
:annonce
ECHO ±±±±±±±±±±±±±±±±±±±±±±±±±±±±INSTALLATION±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±ЙННННННННННННННННННННН»±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±є LE MANOIR HANTE  II є  ±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±ИНННННННННННННННННННННј  ±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±±±                       ±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±ЪДДДДДї±±±±±±±±±±ЪДДДДДї±±±±±±±±±±ЪДДДДДї±±±±±±±±±±ЪДДДДДї±±±±±±±±±±
ECHO ±±±±±±±і  1  і  ±±±±±±±±і  2  і  ±±±±±±±±і  3  і  ±±±±±±±±і  4  і  ±±±±±±±±
ECHO ±±±±ЙННПНННННПНН»±±±±ЙННПНННННПНН»±±±±ЙННПНННННПНН»±±±±ЙННПНННННПНН»±±±±±±±
ECHO ±±±±є Installer є  ±±є Installer є  ±±є Installer є  ±±є Installer є  ±±±±±
ECHO ±±±±є de A … B  є  ±±є de A … C  є  ±±є de A … D  є  ±±є de A … E  є  ±±±±±
ECHO ±±±±ИНННННННННННј  ±±ИНННННННННННј  ±±ИНННННННННННј  ±±ИНННННННННННј  ±±±±±
ECHO ±±±±±±             ±±±±             ±±±±             ±±±±             ±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±ЪДДДДДї±±±±±±±±±±ЪДДДДДї±±±±±±±±±±ЪДДДДДї±±±±±±±±±±ЪДДДДДї±±±±±±±±±±
ECHO ±±±±±±±і  5  і  ±±±±±±±±і  6  і  ±±±±±±±±і  3  і  ±±±±±±±±і  4  і  ±±±±±±±±
ECHO ±±±±ЙННПНННННПНН»±±±±ЙННПНННННПНН»±±±±ЙННПНННННПНН»±±±±ЙННПНННННПНН»±±±±±±±
ECHO ±±±±є Installer є  ±±є Installer є  ±±є Installer є  ±±є Installer є  ±±±±±
ECHO ±±±±є de B … A  є  ±±є de B … C  є  ±±є de B … D  є  ±±є de B … E  є  ±±±±±
ECHO ±±±±ИНННННННННННј  ±±ИНННННННННННј  ±±ИНННННННННННј  ±±ИНННННННННННј  ±±±±±
ECHO ±±±±±±             ±±±±             ±±±±             ±±±±             ±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
goto fin
:continue2
if %3==1 goto installation
if %3==2 goto installation
:annonce3
ECHO ±±±±±±±±±±±±±±±±±±±±±±±±±±±±INSTALLATION±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±ЙННННННННННННННННННННН»±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±є LE MANOIR HANTE  II є  ±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±ИНННННННННННННННННННННј  ±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±±±                       ±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±ЪДДДДДї±±±±±±±±±±ЪДДДДДї±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±і  1  і  ±±±±±±±±і  2  і  ±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±ЙННПНННННПНН»±±±±ЙННПНННННПНН»±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±є    Vous   є  ±±є  Vous ne  є  ±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±є   voulez  є  ±±є voulez pasє  ±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±є formater  є  ±±є formater  є  ±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±є le disque є  ±±є la disque є  ±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±єDESTINATIONє  ±±єDESTINATIONє  ±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±ИНННННННННННј  ±±ИНННННННННННј  ±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±             ±±±±             ±±±±±±±±±±±±±±±±±±±±±±±
goto fin
:continue1
if %2==1 goto continue2
if %2==2 goto continue2
:annonce2
ECHO ±±±±±±±±±±±±±±±±±±±±±±±±±±±±INSTALLATION±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±ЙННННННННННННННННННННН»±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±є LE MANOIR HANTE  II є  ±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±ИНННННННННННННННННННННј  ±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±±±                       ±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±ЪДДДДДї±±±±±±±±±±ЪДДДДДї±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±±і  1  і  ±±±±±±±±і  2  і  ±±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±ЙННПНННННПНН»±±±±ЙННПНННННПНН»±±±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±є    Vous   є  ±±є Imprimanteє  ±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±є  poss‚dez є  ±±є   n'avez  є  ±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±є    une    є  ±±є   pas d'  є  ±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±є imprimanteє  ±±є imprimanteє  ±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±ИНННННННННННј  ±±ИНННННННННННј  ±±±±±±±±±±±±±±±±±±±±±±±
ECHO ±±±±±±±±±±±±±±±±±±±±±±             ±±±±             ±±±±±±±±±±±±±±±±±±±±±±±
goto fin
:installation
if %1==1 goto insAB
if %1==2 goto insAC
if %1==3 goto insAD
if %1==4 goto insAE
if %1==5 goto insBA
if %1==6 goto insBC
if %1==7 goto insBD
if %1==8 goto insBE
ECHO Erreur dans le premier des paramЉtres
goto fin
:insAB
if %3==1 Pause Securit‚ : inserez la disquette vierge dans B: ou dans A: si  vous ne possedez qu'un seul lecteur.
if %3==1 format b:
Pause Inserez la disquette originale dans le lecteur A: et (‚ventuellement) une dis-quette vierge dans B:.
echo on
prompt $s
COPY A:MH2.BAT B:
COPY A:ENTETE.EXE B:
COPY A:ENT2.EXE B:
COPY A:MANOIR2.EXE B:
COPY A:*.CHR B:
COPY A:CGA.BGI B:
COPY A:GR.CST B:
COPY A:MOUSE.COM B:
ECHO OFF
if %2==1 COPY A:GRAPHICS.COM B:
goto fin
:insAC
if %3==1 Pause Securit‚ : inserez la disquette vierge dans C: ou dans A: si  vous ne possedez qu'un seul lecteur.
if %3==1 format c:
Pause Inserez la disquette originale dans le lecteur A: et (‚ventuellement) une dis-quette vierge dans C:.
echo on
prompt $s
COPY A:MH2.BAT C:
COPY A:ENTETE.EXE C:
COPY A:ENT2.EXE C:
COPY A:MANOIR2.EXE C:
COPY A:*.CHR C:
COPY A:CGA.BGI C:
COPY A:GR.CST C:
COPY A:MOUSE.COM C:
if %2==1 COPY A:GRAPHICS.COM C:
goto fin
:insAD
if %3==1 Pause Securit‚ : inserez la disquette vierge dans D: ou dans A: si  vous ne possedez qu'un seul lecteur.
if %3==1 format d:
Pause Inserez la disquette originale dans le lecteur A: et (‚ventuellement) une dis-quette vierge dans D:.
echo on
prompt $s
COPY A:MH2.BAT D:
COPY A:ENTETE.EXE D:
COPY A:ENT2.EXE D:
COPY A:MANOIR2.EXE D:
COPY A:*.CHR D:
COPY A:CGA.BGI D:
COPY A:GR.CST D:
COPY A:MOUSE.COM D:
if %2==1 COPY A:GRAPHICS.COM D:
goto fin
:insAE
if %3==1 format E:
Pause Inserez la disquette originale dans le lecteur A:.
echo on
prompt $s
COPY A:MH2.BAT E:
COPY A:ENTETE.EXE E;
COPY A:ENT2.EXE E:
COPY A:MANOIR2.EXE E:
COPY A:*.CHR E:
COPY A:CGA.BGI E:
COPY A:GR.CST E:
COPY A:MOUSE.COM E:
if %2==1 COPY A:GRAPHICS.COM E:
goto fin
:insBA
if %3==1 Pause Securit‚ : inserez la disquette vierge dans A:.
if %3==1 format a:
Pause Inserez la disquette originale dans le lecteur B: et (‚ventuellement) une dis-quette vierge dans A:.
echo on
prompt $s
COPY B:MH2.BAT A:
COPY B:ENTETE.EXE A;
COPY B:ENT2.EXE A:
COPY B:MANOIR2.EXE A:
COPY B:*.CHR A:
COPY B:CGA.BGI A:
COPY B:GR.CST A:
COPY B:MOUSE.COM A:
if %2==1 COPY B:GRAPHICS.COM A:
goto fin
:insBC
if %3==1 Pause Securit‚ : inserez la disquette vierge dans C: ou dans A: si  vous ne poss‚dez qu'un seul lecteur.
if %3==1 format c:
Pause Inserez la disquette originale dans le lecteur B: et (‚ventuellement) une dis-quette vierge dans C:.
echo on
prompt $s
COPY B:MH2.BAT C:
COPY B:ENTETE.EXE C;
COPY B:ENT2.EXE C:
COPY B:MANOIR2.EXE C:
COPY B:*.CHR C:
COPY B:CGA.BGI C:
COPY B:GR.CST C:
COPY B:MOUSE.COM C:
if %2==1 COPY B:GRAPHICS.COM C:
goto fin
:insBD
if %3==1 Pause Securit‚ : inserez la disquette vierge dans D: ou dans A: si  vous ne poss‚dez qu'un seul lecteur.
if %3==1 format d:
Pause Inserez la disquette originale dans le lecteur B: et (‚ventuellement) une dis-quette vierge dans D:.
echo on
prompt $s
COPY B:MH2.BAT D:
COPY B:ENTETE.EXE D;
COPY B:ENT2.EXE D:
COPY B:MANOIR2.EXE D:
COPY B:*.CHR D:
COPY B:CGA.BGI D:
COPY B:GR.CST D:
COPY B:MOUSE.COM D:
if %2==1 COPY B:GRAPHICS.COM D:
goto fin
:insBE
if %3==1 format E:
Pause Inserez la disquette originale dans le lecteur B:.
echo on
prompt $s
COPY B:MH2.BAT E:
COPY B:ENTETE.EXE E;
COPY B:ENT2.EXE E:
COPY B:MANOIR2.EXE E:
COPY B:*.CHR E:
COPY B:CGA.BGI E:
COPY B:GR.CST E:
COPY B:MOUSE.COM E:
if %2==1 COPY B:GRAPHICS.COM E:
:comm
ECHO ON
Pause Inserez COMMAND.COM dans le lecteur Source.
ECHO OFF
if %1==1 COPY A:COMMAND.COM B:
if %1==2 COPY A:COMMAND.COM C:
if %1==3 COPY A:COMMAND.COM D:
if %1==4 COPY A:COMMAND.COM E:
if %1==5 COPY B:COMMAND.COM A:
if %1==6 COPY B:COMMAND.COM C:
if %1==7 COPY B:COMMAND.COM D:
if %1==8 COPY B:COMMAND.COM E:
:fin
echo on
prompt $p$g
goto ouf
:ouf